image: ilyasemenov/gitlab-ci-git-push

stages:
  - deploy

variables:
  APP_NAME: backend
  APP_URL: update-it-all.dakotaleemartinez.com


deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: https://$APP_NAME.dokku.me/
  only:
    - master
  script:
    - git-push ssh://dokku@$APP_URL:22/$APP_NAME